global
        log 127.0.0.1 local0
        log 127.0.0.1 local1 notice
        #log loghost  local0 info
        maxconn 4096
        #chroot /usr/share/haproxy
        uid 99
        gid 99
        daemon
        #debug
        #quiet
defaults
        log global
        mode http
        option httplog
        option dontlognull
        retries 3
        redispatch
        maxconn 2000
        contimeout 5000
        clitimeout 50000
        srvtimeout 50000
listen http 127.0.0.1:8080
        mode tcp
        option tcplog
        balance roundrobin
        maxconn 10000
        server web01 10.2.2.4:5000 maxconn 5000
        server web02 10.2.2.5:5001 maxconn 5000
listen  appli1-rewrite 0.0.0.0:10001
    cookie  SERVERID rewrite
    balance roundrobin
    server  app1_1 192.168.34.23:8080 cookie app1inst1 check inter 2000 rise 2 fall 5
    server  app1_2 192.168.34.32:8080 cookie app1inst2 check inter 2000 rise 2 fall 5
    server  app1_3 192.168.34.27:8080 cookie app1inst3 check inter 2000 rise 2 fall 5
    server  app1_4 192.168.34.42:8080 cookie app1inst4 check inter 2000 rise 2 fall 5

